import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import UploadFile from '../components/UploadFile/uploadFile'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>

          <a style={{marginTop:24}} href="www.fiyonklu.com/">  <img src="logo.png" alt="" style={{
          maxHeight: '8rem',
        }} /></a>
        </h1>

        <UploadFile></UploadFile>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed by Metin
        </a>
      </footer>
    </div>
  )
}
